name: vocab_box
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  csv: ^6.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.2
  step_progress_indicator: ^1.0.2
  package_info_plus: ^8.2.1
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  file_picker: ^10.1.2
  win32: ^5.5.3
  json_annotation: ^4.9.0
  flutter_slidable: ^4.0.0
  flex_color_scheme: ^8.1.1
  google_fonts: ^6.2.1
  sqflite_common_ffi_web: ^1.0.0
  pretty_diff_text: ^2.1.0
  sqlite3_flutter_libs: ^0.5.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutterfire_cli: ^1.0.0
  json_serializable: ^6.9.0

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#161b22"
  web:
    generate: true
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/word_list_a1.txt
