name: vocab_box
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  csv: ^6.0.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.2
  step_progress_indicator: ^1.0.2
  package_info_plus: ^6.0.0
  firebase_core: ^2.29.0
  cloud_firestore: ^4.16.1
  firebase_auth: ^4.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutterfire_cli: ^1.0.0

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: true
  adaptive_icon_foreground: "assets/icon.png"
  adaptive_icon_background: "#161b22"
  windows:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/word_list_a1.txt
