name: "Build And Deploy Flutter App"

on:
  workflow_dispatch:
    inputs:
      deploy_page:
        type: boolean
        default: true
      create_release:
        type: boolean
        default: true

jobs:
  version:
    uses: ./.github/workflows/_version.yml

  build:
    needs: version
    uses: ./.github/workflows/_build.yml
    with:
      next_version: ${{ needs.version.outputs.next_version }}
      deploy_page: ${{ inputs.deploy_page }}
    secrets: inherit

  release:
    needs: [version, build]
    if: inputs.create_release
    uses: ./.github/workflows/_release.yml
    with:
      next_version: ${{ needs.version.outputs.next_version }}
